import enum


class DivideAttributesHF(enum.Enum):
    """Enum containing Hydrofabric 2.2 divide attribute names"""

    DIVIDE_ID = "divide_id"
    AREA = "areasqkm"
    BEXP = "mode.bexp_soil_layers_stag=1"
    ISLTYP = "mode.ISLTYP"
    IVGTYP = "mode.IVGTYP"
    DKSAT = "geom_mean.dksat_soil_layers_stag=1"
    PSISAT = "geom_mean.psisat_soil_layers_stag=1"
    CWPVT = "mean.cwpvt"
    MFSNO = "mean.mfsno"
    MP = "mean.mp"
    REFKDT = "mean.refkdt"
    SLOPE_1KM = "mean.slope_1km"
    SMCMAX = "mean.smcmax_soil_layers_stag=1"
    SMCWLT = "mean.smcwlt_soil_layers_stag=1"
    VCMX25 = "mean.vcmx25"
    COEFF = "mean.Coeff"
    ZMAX = "mean.Zmax"
    EXPON = "mode.Expon"
    X = "centroid_x"
    Y = "centroid_y"
    IMPERVIOUS = "mean.impervious"
    ELEVATION = "mean.elevation"
    SLOPE = "mean.slope"
    ASPECT = "circ_mean.aspect"
    TWI = "dist_4.twi"
    FLOWPATH_LENGTH = "lengthkm"


class DivideAttributesNHF(enum.Enum):
    """Enum containing NHF divide attribute names"""

    DIVIDE_ID = "div_id"
    AREA = "area_sqkm"
    BEXP = "bexp_mode"
    ISLTYP = "isltyp_mode"
    IVGTYP = "ivgtyp_mode"
    DKSAT = "dksat_geomean"
    PSISAT = "psisat_geommean"
    CWPVT = "cwpvt_mean"
    MFSNO = "msfno_mean"
    MP = ""
    REFKDT = "refkdt_mean"
    SLOPE_1KM = "slope1km_mean"
    SMCMAX = "smcmax_mean"
    SMCWLT = "smcwlt_mean"
    VCMX25 = "vcmx_mean"
    COEFF = ""
    ZMAX = ""
    EXPON = ""
    X = ""
    Y = ""
    IMPERVIOUS = "imperv_mean"
    ELEVATION = "elevation_mean"
    SLOPE = "slope_mean"
    ASPECT = "aspect_circmean"
    FLOWPATH_LENGTH = "length_km"
